name: 'techpulse_dbt'
version: '1.0.0'
config-version: 2

profile: 'techpulse_dbt'

model-paths: ["models"]
test-paths: ["tests"]

models:
  techpulse_dbt:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: incremental